export const formSchema = [
  {
    id: "supplier",
    label: "Supplier",
    type: "searchable",
    inputField: "string",
    options: [
      { id: 1, name: "Valero" },
      { id: 2, name: "Citgo" },
      { id: 3, name: "Marathon" },
      { id: 4, name: "Shell" },
    ],
    required: true,
  },
  {
    id: "shipFrom",
    label: "Ship From Terminal",
    type: "searchable",
    options: [
      { id: 1, name: "Motiva Enterprises LLC-1" },
      { id: 2, name: "Phillips 66 PL - Pasadena" },
      { id: 3, name: "Magellan Pipeline Company L.P.-6" },
      { id: 4, name: "KM Liquids Terminals LLC" },
    ],
    required: true,
  },
  {
    id: "shipVia",
    label: "Ship via",
    type: "searchable",
    options: [
      { id: 1, name: "TTE Company" },
      { id: 2, name: "Always Energy 2" },
      { id: 3, name: "Sunoco Company" },
      { id: 4, name: "Campbell Oil" },
    ],
    required: true,
  },
  {
    id: "paymentTerm",
    label: "Terms",
    type: "searchable",
    options: [
      { id: 1, name: "Net day 1" },
      { id: 2, name: "Net day 7" },
      { id: 3, name: "Net day 10" },
      { id: 4, name: "Net day 15" },
      { id: 4, name: "COD" },
    ],
    required: true,
  },
  {
    id: "taxState",
    label: "Tax state",
    type: "searchable",
    inputField: "string",
    options: [
      { id: 1, name: "Pennsylvania" },
      { id: 2, name: "New York" },
      { id: 3, name: "Ohio" },
      { id: 4, name: "West Virginia" },
    ],
    required: true,
  },
  {
    id: "ref",
    label: "Ref #",
    type: "input",
    required: false,
  },
  {
    id: "invoiceNumber",
    label: "Invoice number",
    type: "input",
    inputField: "number",
    required: true,
  },
  { id: "", label: "", type: "" },
  {
    id: "invoiceDate",
    label: "Invoice date",
    type: "date",
    required: true,
  },
  {
    id: "dueDate",
    label: "Due date",
    type: "date",
    required: true,
  },
  {
    id: "discDueDate",
    label: "Disc due date",
    type: "date",
    required: false,
  },
  {
    id: "postingDate",
    label: "Posting date",
    type: "date",
    required: true,
  },

  {
    id: "paymentMethod",
    label: "Payment Method",
    type: "select",
    inputField: "string",
    options: [
      { label: "Cheque", value: "Cheque" },
      { label: "Credit card", value: "Credit card" },
      { label: "Debit card", value: "Debit card" },
      { label: "UPI", value: "UPI" },
    ],
    required: true,
  },
  {
    id: "paymentOnHold",
    label: "Payment on hold",
    type: "switch",
    required: false,
  },
  {
    id: "contractNumber",
    label: "Contract Number",
    type: "input",
    inputField: "number",
    required: false,
  },
  { id: "", label: "", type: "" },
  {
    id: "deferredInvoiceNumber",
    label: "Deferred invoice number",
    type: "input",
    inputField: "number",
    required: false,
  },
  {
    id: "deferredTaxDueDate",
    label: "Deferred tax due date",
    type: "date",
    required: false,
  },

  {
    id: "listOfProducts",
    label: "Product",
    type: "input",
    options: [
      { id: 1, name: "Product 1" },
      { id: 2, name: "Product 2" },
      { id: 3, name: "Product 3" },
      { id: 4, name: "Product 4" },
    ],
    required: true,
  },
  {
    id: "listOfChartOfAccount",
    label: "Chart of account",
    type: "select",
    inputField: "string",
    options: [
      { label: "Payment Account", value: "Payment Account" },
      { label: "Vendor Account", value: "Vendor Account" },
      { label: "Sales Account", value: "Sales Account" },
      { label: "Purchase Account", value: "Purchase Account" },
    ],
    required: true,
  },
];
